apiVersion: v2
name: oai-5g-basic
type: application
icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png
version: v1.5.0
description: OAI 5G Release 16 Core Network

appVersion: master-v1.5.0

keywords:
  - 5GCN
  - AMF
  - SMF
  - NRF
  - UPF
  - UDM
  - UDR
  - AUSF

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org

dependencies:
- condition: mysql.enabled
  name: mysql
  repository: "file://../0-mysql"
  version: 8.0.31
- condition: oai-nrf.enabled
  name: oai-nrf
  repository: "file://../1-nrf"
  version: v1.5.0
- condition: oai-udr.enabled
  name: oai-udr
  repository: "file://../2-udr"
  version: v1.5.0
- condition: oai-udm.enabled
  name: oai-udm
  repository: "file://../3-udm"
  version: v1.5.0
- condition: oai-ausf.enabled
  name: oai-ausf
  repository: "file://../4-ausf"
  version: v1.5.0
- condition: oai-amf.enabled
  name: oai-amf
  repository: "file://../5-amf"
  version: v1.5.0
- condition: oai-smf.enabled
  name: oai-smf
  repository: "file://../7-smf"
  version: v1.5.0
- condition: oai-upf.enabled
  name: oai-spgwu-tiny
  repository: "file://../6-upf"
  version: v1.5.0

