mysql:
  enabled: true
  weight: 0
  imagePullPolicy: IfNotPresent
  oai5gdatabase: basic
  imagePullSecrets:
    - name: regcred
  persistence:
    enabled: false

oai-nrf:
  enabled: true
  weight: 0
  start:
    tcpdump: false
  service:
    type: ClusterIP
    clusterIP: 10.233.19.104
  nrfImage:
    registry: docker.io
    repository: oaisoftwarealliance/oai-nrf
    tag: v1.5.0
    pullPolicy: IfNotPresent
  nrfConfig:
    tz: "Europe/Paris"
    nrfApiVersion: "v1"
    nrfInterfaceHttp2PortForSBI: "8080"
    nrfInterfaceNameForSBI: "eth0"
    nrfInterfacePortForSBI: "80"
    instance: "0"
    pidDirectory: "/var/run"

oai-udr:
  enabled: true
  weight: 1
  start:
    tcpdump: false
  service:
    type: ClusterIP
    clusterIP: 10.233.51.216
  nrfImage:
    registry: docker.io
    repository: oaisoftwarealliance/oai-udr
    tag: v1.5.0
    pullPolicy: IfNotPresent
  udrConfig:
    instance: "0"
    mySqlDb: "oai_db"
    mySqlPass: "linux"
    mySqlServer: "mysql"
    mySqlUser: "root"
    waitMysql: "120"
    dbConnectionTimeout: "300"
    nrfApiVersion: "v1"
    nrfFqdn: "oai-nrf-svc"
    nrfPort: "80"
    pidDirectory: "/var/run"
    registerNrf: "yes"
    sbiIfName: "eth0"
    sbiPortHttp1: "80"
    sbiPortHttp2: "8080"
    tz: "Europe/Paris"
    udrApiVersion: "v1"
    udrName: "oai-udr"
    useFqdnDns: "no"
    usehttp2: "no"

oai-udm:
  enabled: true
  weight: 2

oai-ausf:
  enabled: true
  weight: 3

oai-amf:
  enabled: true
  weight: 4
  multus:
    create: false

oai-upf:
  enabled: true
  weight: 5
  multus:
    create: false

oai-smf:
  enabled: true
  weight: 6
  multus:
    create: false
