---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc-ngu
  labels:
    {{- include "oai-spgwu-tiny.labels" . | nindent 4 }}
spec:
  type: NodePort
  clusterIP: {{ .Values.service.nguClusterIp }}
  ports:
    - name: oai-spgwu-tiny
      port: {{ .Values.service.nguPort }}
      targetPort: 2152
      protocol: TCP
      nodePort: {{ .Values.service.nguNodePort }}
  selector:
    {{- include "oai-spgwu-tiny.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "oai-spgwu-tiny.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.pfcpClusterIp }}
  ports:
    - name: pfcp
      port: {{ .Values.service.pfcpPort }}
      targetPort: 8805
      protocol: UDP
  selector:
    {{- include "oai-spgwu-tiny.selectorLabels" . | nindent 4 }}