---
apiVersion: v1
kind: Service
metadata:
  namespace: oai-5gcn
  name: oai-spgwu-tiny-svc-ngu
  labels:
    helm.sh/chart: oai-spgwu-tiny-v1.5.0
    app.kubernetes.io/name: oai-spgwu-tiny
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.5.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  clusterIP: 10.233.45.210
  ports:
    - name: oai-spgwu-tiny
      port: 2152
      targetPort: 2152
      protocol: TCP
      nodePort: 32152
  selector:
    app.kubernetes.io/name: oai-spgwu-tiny
    app.kubernetes.io/instance: release-name
---
apiVersion: v1
kind: Service
metadata:
  namespace: oai-5gcn
  name: oai-spgwu-tiny-svc
  labels:
    helm.sh/chart: oai-spgwu-tiny-v1.5.0
    app.kubernetes.io/name: oai-spgwu-tiny
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.5.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: 10.233.45.211
  ports:
    - name: pfcp
      port: 8805
      # Port to forward to inside the pod
      targetPort: 8805
      protocol: UDP
  selector:
    app.kubernetes.io/name: oai-spgwu-tiny
    app.kubernetes.io/instance: release-name
