apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-udr.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-udr.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-udr.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets.create }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets.pullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: tcpdump
        image: "{{ .Values.tcpdumpImage.registry }}/{{ .Values.tcpdumpImage.repository }}:{{ .Values.tcpdumpImage.version }}"
        imagePullPolicy: {{ .Values.tcpdumpImage.pullPolicy }}
        {{- if .Values.resources.enabled}}
        resources:
          requests:
            memory: {{ .Values.resources.tcpdump.requests.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.tcpdump.limits.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -i any -w /pcap/{{ .Chart.Name }}_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistence.enabled}}
        volumeMounts:
        - mountPath: "/pcap"
          name: tcpdump-5gcn-volume
        {{- end}}
      - name: udr
        image: "{{ .Values.udrImage.registry }}/{{ .Values.udrImage.repository }}:{{ .Values.udrImage.version }}"
        imagePullPolicy: {{ .Values.udrImage.pullPolicy }}
        {{- if .Values.resources.enabled}}
        resources:
          requests:
            memory: {{ .Values.resources.udr.requests.memory | quote }}
            cpu: {{ .Values.resources.udr.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.udr.limits.memory | quote }}
            cpu: {{ .Values.resources.udr.limits.cpu | quote }}
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.readinessProbe}}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udr/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        {{- end}}
        {{- if .Values.livenessProbe}}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udr/bin/healthcheck.sh
          initialDelaySeconds: 15
          periodSeconds: 5
        {{- end}}
        ports:
        - containerPort: {{ .Values.udrConfig.sbiPortHttp1 }}
          name: http1
        - containerPort: {{ .Values.udrConfig.sbiPortHttp2 }}
          name: http2
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tz
          - name: UDR_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrName
          - name: INSTANCE
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: instance
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pidDirectory
          - name: USE_FQDN_DNS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: useFqdnDns
          - name: UDR_INTERFACE_NAME_FOR_NUDR
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiIfName
          - name: REGISTER_NRF
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: registerNrf
          - name: USE_HTTP2
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: usehttp2
          - name: UDR_INTERFACE_PORT_FOR_NUDR
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiPortHttp1
          - name: UDR_INTERFACE_HTTP2_PORT_FOR_NUDR
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiPortHttp2
          - name: UDR_API_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrApiVersion
          - name: NRF_IPV4_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfIpv4Address
          - name: NRF_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfPort
          - name: NRF_API_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfApiVersion
          - name: NRF_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfFqdn
          - name: MYSQL_IPV4_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mySqlServer
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mySqlUser
          - name: DB_CONNECTION_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: dbConnectionTimeout
          - name: MYSQL_PASS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mySqlPass
          - name: MYSQL_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mySqlDb
          - name: WAIT_MYSQL
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: waitMysql
      volumes:
      {{- if .Values.persistence.enabled}}
      - name: tcpdump-5gcn-volume
        persistenceVolumeClaim:
          claimName: {{ .Values.persistence.tcpdump.claimName }}
      {{-end}}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- if .Values.serviceAccount.enabled}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{-end}}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
