apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    {{- include "oai-udr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: http1
      port: {{ .Values.udrConfig.sbiPortHttp1 }}
      targetPort: 80
      protocol: TCP
    - name: http2
      port: {{ .Values.udrConfig.sbiPortHttp2 }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "oai-udr.selectorLabels" . | nindent 4 }}