apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    {{- include "oai-nrf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: http1
      port: {{ .Values.nrfConfig.nrfInterfacePortForSBI }}
      targetPort: 80
      protocol: TCP
    - name: http2
      port: {{ .Values.nrfConfig.nrfInterfaceHttp2PortForSBI }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "oai-nrf.selectorLabels" . | nindent 4 }}