{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Chart.Name }}-n2-net1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "mode": "bridge",
      "master": {{- cat .Values.multus.hostInterface | nospace | quote }},
        "ipam": {
          "type": "static",
          "addresses": [
            {
              "address": {{- cat .Values.multus.n2IpAdd "/" .Values.multus.n2Netmask | nospace | quote }}
            }
          ]
        }
      }'
{{- end }}
