# Source: oai-amf/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oai-5gcn
  name: oai-amf
  labels:
    helm.sh/chart: oai-amf-v1.5.0
    app.kubernetes.io/name: oai-amf
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.5.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-amf
      app.kubernetes.io/instance: release-name
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-amf
        app.kubernetes.io/instance: release-name
    {{- if .Values.multus.create }}
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
          [{
                 "name": "oai-amf-n2-net1",
                 "default-route": ["172.21.11.254"]
          }]
    {{- end }}
    spec:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      imagePullSecrets:
                - name: regcred
      containers:
      - name: tcpdump
        image: "docker.io/corfr/tcpdump:latest"
        imagePullPolicy: IfNotPresent
        securityContext:
            privileged: false
        command:
          - /bin/sleep
          - infinity
      - name: amf
        image: "docker.io/oaisoftwarealliance/oai-amf:v1.5.0"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /openair-amf/etc
            name: configuration
        securityContext:
            privileged: false
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-amf/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        ports:
        - containerPort: 38412
          name: oai-amf
          protocol: SCTP
        - containerPort: 80
          name: http1
          protocol: TCP
        - containerPort: 8080
          name: http2
          protocol: TCP
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: oai-amf-configmap-variables
                key: tz
          - name: INSTANCE
            valueFrom:
              configMapKeyRef:
                name: oai-amf-configmap-variables
                key: instance
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: oai-amf-configmap-variables
                key: pidDirectory
          - name: OPERATOR_KEY
            valueFrom:
              configMapKeyRef:
                name: oai-amf-configmap-variables
                key: operatorKey
        command:
          - /openair-amf/bin/oai_amf
          - -c
          - /openair-amf/etc/amf.conf
          - -o
      volumes:
      - configMap:
          name: oai-amf-configmap
        name: configuration
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: oai-amf-sa
      terminationGracePeriodSeconds: 5
