apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-amf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "oai-amf.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-amf.selectorLabels" . | nindent 8 }}
    {{- if .Values.multus.create }}
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
          [{
            "name": "{{ .Chart.Name }}-n2-net1",
            "default-route": ["{{ .Values.multus.n2Gateway }}"]
          }]
    {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets.create }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets.pullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: tcpdump
        image: "{{ .Values.tcpdumpImage.registry }}/{{ .Values.tcpdumpImage.repository }}:{{ .Values.tcpdumpImage.tag }}"
        imagePullPolicy: {{ .Values.tcpdumpImage.pullPolicy }}
        securityContext:
          privileged: false
        {{- if .Values.resources.enabled}}
        resources:
          requests:
            memory: {{ .Values.resources.tcpdump.requests.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.tcpdump.limits.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -i any -w /pcap/{{ .Chart.Name }}_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistence.enabled}}
        volumeMounts:
        - mountPath: "/pcap"
          name: tcpdump-5gcn-volume
        {{- end}}
      - name: amf
        image: "{{ .Values.amfImage.registry }}/{{ .Values.amfImage.repository }}:{{ .Values.amfImage.tag }}"
        imagePullPolicy: {{ .Values.amfImage.pullPolicy }}
        volumeMounts:
          - mountPath: /openair-amf/etc
            name: configuration
        {{- if .Values.resources.enabled}}
        resources:
          requests:
            memory: {{ .Values.resources.amf.requests.memory | quote }}
            cpu: {{ .Values.resources.amf.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.amf.limits.memory | quote }}
            cpu: {{ .Values.resources.amf.limits.cpu | quote }}
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.readinessProbe}}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-amf/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        {{- end}}
        {{- if .Values.livenessProbe}}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-amf/bin/healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        {{- end}}
        ports:
        - containerPort: {{ .Values.service.ngap.port }}
          name: oai-amf
          protocol: SCTP
        - containerPort: {{ .Values.amfParameters.sbiPortHttp1 }}
          name: http1
          protocol: TCP
        - containerPort: {{ .Values.amfParameters.sbiPortHttp2 }}
          name: http2
          protocol: TCP
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: oai-amf-configmap-variables
                key: tz
          - name: INSTANCE
            valueFrom:
              configMapKeyRef:
                name: oai-amf-configmap-variables
                key: instance
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: oai-amf-configmap-variables
                key: pidDirectory
          - name: OPERATOR_KEY
            valueFrom:
              configMapKeyRef:
                name: oai-amf-configmap-variables
                key: operatorKey
        {{- if .Values.start.amf}}
        command:
          - /openair-amf/bin/oai_amf
          - -c
          - /openair-amf/etc/amf.conf
          - -o
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
      volumes:
      {{- if .Values.persistence.enabled}}
      - name: tcpdump-5gcn-volume
        persistenceVolumeClaim:
          claimName: {{ .Values.persistence.tcpdump.claimName }}
      {{- end}}
      - name: configuration
        configMap:
          name: {{ .Chart.Name }}-configmap
          items:
          - key: amfConfiguration
            path: amf.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- if .Values.serviceAccount.enabled}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end}}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}