---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc-ngap
  labels:
    {{- include "oai-amf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ngap.type }}
  clusterIP: {{ .Values.service.ngap.clusterIP }}
  ports:
  - name: oai-amf
    port: {{ .Values.service.ngap.port }}
    targetPort: 38412
    protocol: SCTP
    nodePort: {{ .Values.service.ngap.nodePort }}
  selector:
    {{- include "oai-amf.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    {{- include "oai-amf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: http1
      port: {{ .Values.amfParameters.sbiPortHttp1 }}
      targetPort: 80
      protocol: TCP
    - name: http2
      port: {{ .Values.amfParameters.sbiPortHttp2 }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "oai-amf.selectorLabels" . | nindent 4 }}