{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: oai-5gcn
  name: oai-amf-n2-net1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "mode": "bridge",
      "master":"eno2.100",
        "ipam": {
            "type": "static",
            "addresses": [
                  {
                        "address":"172.21.10.6/22"
                  }
          ]
        }
      }'
{{- end }}
