replicas: 1

imagePullSecrets:
  create: false
  pullSecrets:
    - name: ""

start:
  tcpdump: false

service:
  type: ClusterIP
  clusterIP: 10.233.51.216

ausfImage:
  registry: docker.io
  repository: oaisoftwarealliance/oai-ausf
  tag: v1.5.0
  pullPolicy: IfNotPresent

tcpdumpImage:
  registry: docker.io
  repository: corfr/tcpdump
  tag: latest
  pullPolicy: IfNotPresent

ausfConfig:
  ausfName: "oai-ausf"
  instanceId: "0"
  nrfApiVersion: "v1"
  nrfFqdn: "oai-nrf-svc"
  nrfIpAddress: "10.233.19.104"
  nrfPort: "80"
  pidDirectory: "/var/run"
  registerNrf: "yes"
  sbiIfName: "eth0"
  sbiPortHttp1: "80"
  sbiPortHttp2: "8080"
  tz: "Europe/Paris"
  udmFqdn: "oai-udm-svc"
  udmIpAddress: "10.233.58.64"
  udmPort: "80"
  udmVersionNb: "v1"
  useFqdnDns: "no"
  useHttp2: "no"

serviceAccount:
  enabled: true
  name: "oai-ausf-sa"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: false

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  tcpdump:
    claimName: oai-ausf-tcpdump
    size: 1Gi

resources:
  enabled: false
  limits:
    tcpdump:
      cpu: 100m
      memory: 128Mi
    ausf:
      cpu: 100m
      memory: 128Mi
  requests:
    tcpdump:
      cpu: 100m
      memory: 128Mi
    ausf:
      cpu: 100m
      memory: 128Mi

readinessProbe: true
livenessProbe: false
terminationGracePeriodSeconds: 5
nodeSelector: {}
nodeName: