replicas: 1

imagePullSecrets:
  create: false
  pullSecrets:
    - name: ""

start:
  tcpdump: false

service:
  type: ClusterIP
  clusterIP: 10.233.58.64

udmImage:
  registry: docker.io
  repository: oaisoftwarealliance/oai-udm
  tag: v1.5.0
  pullPolicy: IfNotPresent

tcpdumpImage:
  registry: docker.io
  repository: corfr/tcpdump
  tag: latest
  pullPolicy: IfNotPresent

udmConfig:
  instance: "0"
  nrfRegistration: "yes"
  nrfApiVersionNb: "v1"
  nrfFqdn: "oai-nrf-svc"
  nrfIpAddress: "10.233.19.104"
  nrfPort: "80"
  pidDirectory: "/var/run"
  sbiIfName: "eth0"
  sbiPortHttp1: "80"
  sbiPortHttp2: "8080"
  tz: "Europe/Paris"
  udmApiVersionNb: "v1"
  udmName: "oai-udm"
  udrApiVersionNb: "v1"
  udrFqdn: "oai-udr-svc"
  udrIpAddress: "10.233.51.216"
  udrPort: "80"
  useFqdnDns: "no"
  useHttp2: "no"

serviceAccount:
  enabled: true
  name: "oai-udm-sa"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: false

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  tcpdump:
    claimName: oai-udm-tcpdump
    size: 1Gi

resources:
  enabled: false
  limits:
    tcpdump:
      cpu: 100m
      memory: 128Mi
    udm:
      cpu: 100m
      memory: 128Mi
  requests:
    tcpdump:
      cpu: 100m
      memory: 128Mi
    udm:
      cpu: 100m
      memory: 128Mi

readinessProbe: false
livenessProbe: false
terminationGracePeriodSeconds: 5
nodeSelector: {}
nodeName: