global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fastapi-application"
    scrape_interval: 5s
    static_configs:
      - targets: ["fastapi-application:8001"]