apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-udm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-udm.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-udm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets.create }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets.pullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: tcpdump
        image: "{{ .Values.tcpdumpImage.registry }}/{{ .Values.tcpdumpImage.repository }}:{{ .Values.tcpdumpImage.tag }}"
        imagePullPolicy: {{ .Values.tcpdumpImage.pullPolicy }}
        {{- if .Values.resources.enabled}}
        resources:
          requests:
            memory: {{ .Values.resources.tcpdump.requests.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.tcpdump.limits.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sleep
          - infinity
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistence.enabled}}
        volumeMounts:
        - mountPath: "/pcap"
          name: tcpdump-5gcn-volume
        {{- end}}
      - name: udm
        image: "{{ .Values.udmImage.registry }}/{{ .Values.udmImage.repository }}:{{ .Values.udmImage.tag }}"
        imagePullPolicy: {{ .Values.udmImage.pullPolicy }}
        {{- if .Values.resources.enabled}}
        resources:
          requests:
            memory: {{ .Values.resources.udm.requests.memory | quote }}
            cpu: {{ .Values.resources.udm.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.udm.limits.memory | quote }}
            cpu: {{ .Values.resources.udm.limits.cpu | quote }}
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- if .Values.readinessProbe}}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udm/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        {{- end}}
        {{- if .Values.livenessProbe}}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udm/bin/healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        {{- end}}
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: tz
          - name: INSTANCE
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: instance
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: pidDirectory
          - name: UDM_NAME
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: udmName
          - name: SBI_IF_NAME
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: sbiIfName
          - name: SBI_PORT
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: sbiPortHttp1
          - name: SBI_HTTP2_PORT
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: sbiPortHttp2
          - name: USE_HTTP2
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: useHttp2
          - name: UDM_VERSION_NB
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: udmApiVersionNb
          - name: USE_FQDN_DNS
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: useFqdnDns
          - name: UDR_IP_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: udrIpAddress
          - name: UDR_PORT
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: udrPort
          - name: UDR_VERSION_NB
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: udrApiVersionNb
          - name: UDR_FQDN
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: udrFqdn
          - name: REGISTER_NRF
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: nrfRegistration
          - name: NRF_IPV4_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: nrfIpAddress
          - name: NRF_PORT
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: nrfPort
          - name: NRF_API_VERSION
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: nrfApiVersionNb
          - name: NRF_FQDN
            valueFrom:
              configMapKeyRef:
                name: oai-udm-configmap
                key: nrfFqdn
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udm/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        securityContext:
            privileged: false
        ports:
        - containerPort: {{ .Values.udmConfig.sbiPortHttp1 }}
          name: http1
        - containerPort: {{ .Values.udmConfig.sbiPortHttp2 }}
          name: http2
      volumes:
      {{- if .Values.persistence.enabled}}
      - name: tcpdump-5gcn-volume
        persistenceVolumeClaim:
          claimName: {{ .Values.persistence.tcpdump.claimName }}
      {{- end}}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- if .Values.serviceAccount.enabled}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end}}
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
