# Source: oai-udm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: oai-5gcn
  name: oai-udm-svc
  labels:
    helm.sh/chart: oai-udm-v1.5.0
    app.kubernetes.io/name: oai-udm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.5.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: 10.233.58.64
  ports:
    - name: http1
      # Port accessible outside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 80
      protocol: TCP
    - name: http2
      # Port accessible outside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: oai-udm
    app.kubernetes.io/instance: release-name
