replicas: 1

imagePullSecrets:
  create: false
  pullSecrets:
    - name: ""

start:
  tcpdump: false

service:
  type: ClusterIP
  clusterIP: 10.233.51.216

udrImage:
  registry: docker.io
  repository: oaisoftwarealliance/oai-udr
  tag: v1.5.0
  pullPolicy: IfNotPresent

tcpdumpImage:
  registry: docker.io
  repository: corfr/tcpdump
  version: latest
  pullPolicy: IfNotPresent

udrConfig:
  instance: "0"
  mySqlDb: "oai_db"
  mySqlPass: "linux"
  mySqlServer: "mysql"
  mySqlUser: "root"
  waitMysql: "120"
  dbConnectionTimeout: "300"
  nrfApiVersion: "v1"
  nrfFqdn: "oai-nrf-svc"
  nrfPort: "80"
  pidDirectory: "/var/run"
  registerNrf: "yes"
  sbiIfName: "eth0"
  sbiPortHttp1: "80"
  sbiPortHttp2: "8080"
  tz: "Europe/Paris"
  udrApiVersion: "v1"
  udrName: "oai-udr"
  useFqdnDns: "no"
  usehttp2: "no"

serviceAccount:
  enabled: true
  name: "oai-udr-sa"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: false

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  tcpdump:
    claimName: oai-udr-tcpdump
    size: 1Gi

resources:
  enabled: false
  limits:
    tcpdump:
      cpu: 100m
      memory: 128Mi
    udr:
      cpu: 100m
      memory: 128Mi
  requests:
    tcpdump:
      cpu: 100m
      memory: 128Mi
    udr:
      cpu: 100m
      memory: 128Mi

readinessProbe: true
livenessProbe: false
terminationGracePeriodSeconds: 5
nodeSelector: {}
nodeName: