apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-initialization
  namespace: {{ .Release.Namespace }}
data:
{{- if eq .Values.oai5gdatabase "mini" }}
  {{ (.Files.Glob "initialization/oai_db-mini.sql").AsConfig | indent 2 | trim }}
{{- else }}
  {{ (.Files.Glob "initialization/oai_db-basic.sql").AsConfig | indent 2 | trim }}
{{- end }}
