# Source: oai-smf/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-smf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "oai-smf.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-smf.selectorLabels" . | nindent 8 }}
    {{- if .Values.multus.create }}
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
          [{
                 "name": "oai-smf-n4-net1",
                 "default-route": ["172.21.7.254"]
          }]
    {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets.create }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets.pullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: tcpdump
        image: "{{ .Values.tcpdumpImage.registry }}/{{ .Values.tcpdumpImage.repository }}:{{ .Values.tcpdumpImage.tag }}"
        imagePullPolicy: {{ .Values.tcpdumpImage.pullPolicy }}
        securityContext:
          privileged: false
        {{- if .Values.resources.enabled}}
        resources:
          requests:
            memory: {{ .Values.resources.tcpdump.requests.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.tcpdump.limits.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -i any -w /pcap/{{ .Chart.Name }}_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistence.enabled}}
        volumeMounts:
        - mountPath: "/pcap"
          name: tcpdump-5gcn-volume
        {{- end}}
      - name: smf
        image: "{{ .Values.smfImage.registry }}/{{ .Values.smfImage.repository }}:{{ .Values.smfImage.tag }}"
        imagePullPolicy: {{ .Values.smfImage.pullPolicy }}
        volumeMounts:
          - mountPath: /openair-smf/etc
            name: configuration
        {{- if .Values.resources.enabled}}
        resources:
          requests:
            memory: {{ .Values.resources.smf.requests.memory | quote }}
            cpu: {{ .Values.resources.smf.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.smf.limits.memory | quote }}
            cpu: {{ .Values.resources.smf.limits.cpu | quote }}
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.readinessProbe}}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-smf/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        {{- end}}
        {{- if .Values.livenessProbe}}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-smf/bin/healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        {{- end}}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: oai-smf
        - containerPort: {{ .Values.smfParameters.sbiPortHttp1 }}
          name: http1
        - containerPort: {{ .Values.smfParameters.sbiPortHttp2 }}
          name: http2
        {{- if .Values.start.smf}}
        command:
          - /openair-smf/bin/oai_smf
          - -c
          - /openair-smf/etc/smf.conf
          - -o
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
      volumes:
      {{- if .Values.persistence.enabled}}
      - name: tcpdump-5gcn-volume
        persistenceVolumeClaim:
          claimName: {{ .Values.persistence.tcpdump.claimName }}
      {{- end}}
      - name: configuration
        configMap:
          name: {{ .Chart.Name }}-configmap
          items:
          - key: smfConfiguration
            path: smf.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- if .Values.serviceAccount.enabled}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end}}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
