{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: oai-5gcn
  name: oai-smf-n4-net1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master":"eno1.100",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address":"172.21.6.202/22",
                        "gateway": "172.21.7.254"
                }
        ]
      }
    }'
{{- end }}
