apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    {{- include "oai-smf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "oai-smf.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.multus.create }}
    - name: oai-smf
      port: {{ .Values.service.port }}
      targetPort: 8805
      protocol: UDP
    {{ end }}
    - name: http1
      port: {{ .Values.smfParameters.sbiPortHttp1 }}
      targetPort: 80
      protocol: TCP
    - name: http2
      port: {{ .Values.smfParameters.sbiPortHttp2 }}
      targetPort: 8080
      protocol: TCP